# -*- coding: utf-8 -*-
"""Project 101.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qoGD2p4ix_qU4-o9uxmkHRtfX2nTCklf
"""

!pip install shap xgboost lightgbm kaggle

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_absolute_error, mean_squared_error

import xgboost as xgb
import shap

plt.style.use("seaborn-v0_8")

import kagglehub

# Download latest version
path = kagglehub.dataset_download("pratyushakar/rossmann-store-sales")

print("Path to dataset files:", path)

import os

dataset_path = "/root/.cache/kagglehub/datasets/pratyushakar/rossmann-store-sales/versions/3"

os.listdir(dataset_path)

import pandas as pd

train_path = os.path.join(dataset_path, "train.csv")
store_path = os.path.join(dataset_path, "store.csv")

df = pd.read_csv(train_path, parse_dates=["Date"])
stores = pd.read_csv(store_path)

df = df.merge(stores, on="Store", how="left")
df.head()

plt.figure(figsize=(14,5))
df[df["Store"] == 1].sort_values("Date") \
  .set_index("Date")["Sales"] \
  .plot(title="Store 1 – Daily Sales")

plt.ylabel("Sales")
plt.show()

df = df[df["Open"] == 1]
df = df[df["Sales"] > 0]

df.isnull().sum()

df["StateHoliday"] = df["StateHoliday"].astype(str)
df.fillna(0, inplace=True)

df.isnull().sum()

df["day_of_week"] = df["Date"].dt.dayofweek
df["week_of_year"] = df["Date"].dt.isocalendar().week.astype(int)
df["month"] = df["Date"].dt.month
df["year"] = df["Date"].dt.year
df["is_weekend"] = df["day_of_week"].isin([5,6]).astype(int)

df = df.sort_values(["Store", "Date"])

lags = [1, 7, 14, 28]
for lag in lags:
    df[f"sales_lag_{lag}"] = df.groupby("Store")["Sales"].shift(lag)

# Encode categorical store features
df["StoreType"] = df["StoreType"].astype("category").cat.codes
df["Assortment"] = df["Assortment"].astype("category").cat.codes

windows = [7, 14, 28]
for window in windows:
    df[f"rolling_mean_{window}"] = (
        df.groupby("Store")["Sales"]
        .shift(1)
        .rolling(window)
        .mean()
    )

sample_store = 1
store_df = df[df["Store"] == sample_store]

plt.figure(figsize=(14,5))
plt.plot(store_df["Date"], store_df["Sales"], label="Actual Sales")
plt.plot(store_df["Date"], store_df["rolling_mean_7"], label="7-day Rolling Mean")
plt.legend()
plt.title("Sales vs Rolling Mean")
plt.show()

features = [
    "day_of_week", "week_of_year", "month", "is_weekend",
    "Promo", "SchoolHoliday",
    "sales_lag_1", "sales_lag_7", "sales_lag_14", "sales_lag_28",
    "rolling_mean_7", "rolling_mean_14", "rolling_mean_28"
]

df_model = df.dropna(subset=features + ["Sales"])

X = df_model[features]
y = df_model["Sales"]

split_date = "2015-06-01"

X_train = X[df_model["Date"] < split_date]
X_test  = X[df_model["Date"] >= split_date]
y_train = y[df_model["Date"] < split_date]
y_test  = y[df_model["Date"] >= split_date]

model = xgb.XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

plt.figure(figsize=(14,5))
plt.plot(y_test.values[:200], label="Actual")
plt.plot(y_pred[:200], label="Predicted")
plt.legend()
plt.title("Prediction vs Actual (Sample)")
plt.show()

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print(f"RMSE: {rmse:.2f}")
print(f"MAE : {mae:.2f}")

df_model["Sales"].describe()

errors = y_test - y_pred

plt.figure(figsize=(10,5))
sns.histplot(errors, bins=50, kde=True)
plt.title("Prediction Error Distribution")
plt.xlabel("Error (Actual - Predicted)")
plt.show()

explainer = shap.Explainer(model)
shap_values = explainer(X_test)

shap.summary_plot(shap_values, X_test)

index = 10

shap.plots.waterfall(shap_values[index])

what_if = X_test.iloc[[index]].copy()
what_if["Promo"] = 0

original_pred = model.predict(X_test.iloc[[index]])[0]
new_pred = model.predict(what_if)[0]

print(f"With Promo    : {original_pred:.0f}")
print(f"Without Promo : {new_pred:.0f}")

"""Visualize Raw Sales vs Rolling Mean"""

sample_store = 1

store_df = (
    df[df["Store"] == sample_store]
    .sort_values("Date")
    .set_index("Date")
)

plt.figure(figsize=(16,6))

plt.plot(
    store_df.index,
    store_df["Sales"],
    label="Raw Daily Sales",
    alpha=0.4
)

plt.plot(
    store_df.index,
    store_df["rolling_mean_7"],
    label="7-day Rolling Mean",
    linewidth=2
)

plt.plot(
    store_df.index,
    store_df["rolling_mean_28"],
    label="28-day Rolling Mean",
    linewidth=3
)

plt.title(f"Raw Sales vs Rolling Mean – Store {sample_store}", fontsize=14)
plt.ylabel("Sales")
plt.xlabel("Date")
plt.legend()
plt.show()

"""Final Explanation Plots"""

plt.figure(figsize=(16,6))

sample = 300  # first 300 days
plt.plot(y_test.values[:sample], label="Actual Sales", linewidth=2)
plt.plot(y_pred[:sample], label="Predicted Sales", linewidth=2)

plt.title("Actual vs Predicted Sales (Sample Period)")
plt.ylabel("Sales")
plt.xlabel("Days")
plt.legend()
plt.show()

plt.figure(figsize=(16,6))

plt.plot(store_df.index, store_df["Sales"],
         label="Daily Sales", alpha=0.4)

plt.plot(store_df.index, store_df["rolling_mean_7"],
         label="7-day Average", linewidth=2)

plt.plot(store_df.index, store_df["rolling_mean_28"],
         label="28-day Average", linewidth=3)

plt.title("Daily Sales vs Short-term and Long-term Trends")
plt.ylabel("Sales")
plt.xlabel("Date")
plt.legend()
plt.show()

promo_effect = df_model.groupby("Promo")["Sales"].mean()

promo_effect.plot(
    kind="bar",
    figsize=(6,4),
    title="Average Sales: Promotion vs No Promotion",
    ylabel="Average Sales",
    rot=0
)

plt.show()

plt.figure(figsize=(10,5))

plt.hist(np.abs(errors), bins=40)
plt.title("How Big Are the Prediction Errors?")
plt.xlabel("Absolute Error (Units)")
plt.ylabel("Number of Days")

plt.show()

shap_importance = np.abs(shap_values.values).mean(axis=0)

importance_df = pd.DataFrame({
    "Feature": X_test.columns,
    "Impact": shap_importance
}).sort_values("Impact", ascending=True)

plt.figure(figsize=(8,6))
plt.barh(importance_df["Feature"], importance_df["Impact"])
plt.title("Main Factors That Influence Sales Predictions")
plt.xlabel("Average Impact on Prediction")
plt.show()